-- CREATE TABLE
CREATE TABLE PRMS_TRANSACTION
(
  ENTITY_NUMBER        NUMBER(4) NOT NULL,
  BRANCH_CODE          VARCHAR2(6) NOT NULL,
  EMP_ID               VARCHAR2(20) NOT NULL,
  SAL_YEAR             NUMBER(4) NOT NULL,
  MONTH_CODE           NUMBER(2) NOT NULL,
  SAL_MONTH            VARCHAR2(10),
  BASIC_PAY            NUMBER(9,2),
  MEDICAL_ALLOWANCE    NUMBER(9,2),
  HOUSE_RENT_ALLOWANCE NUMBER(9,2),
  TEL_ALLOWANCE        NUMBER(9,2),
  TRANS_ALLOWANCE      NUMBER(9,2),
  EDU_ALLOWANCE        NUMBER(9,2),
  WASH_ALLOWANCE       NUMBER(9,2),
  PENSION_ALLOWANCE    NUMBER(9,2),
  ENTERTAINMENT        NUMBER(9,2),
  DOMESTIC_ALLOWANCE   NUMBER(9,2),
  OTHER_ALLOWANCE      NUMBER(9,2),
  GROSS_PAY_AMT        NUMBER(9,2),
  HBADV_DEDUC          NUMBER(9,2),
  MCYCLE_DEDUC         NUMBER(9,2),
  BICYCLE_DEDUC        NUMBER(9,2),
  PFADV_DEDUC          NUMBER(9,2),
  PENSION_DEDUC        NUMBER(9,2),
  REVENUE_DEDUC        NUMBER(5,2),
  WELFARE_DEDUC        NUMBER(9,2),
  CARFARE_DEDUC        NUMBER(9,2),
  CARUSE_DEDUC         NUMBER(9,2),
  GAS_BILL             NUMBER(9,2),
  WATER_BILL           NUMBER(9,2),
  ELECTRICITY_BILL     NUMBER(9,2),
  HOUSE_RENT_DEDUC     NUMBER(9,2),
  NEWS_PAPER_DEDUC     NUMBER(5,2),
  NET_DED_AMT          NUMBER(9,2),
  NET_PAY_AMT          NUMBER(9,2),
  PF_DEDUCTION         NUMBER(9,2),
  HBADV_ARREAR_DEDUC   NUMBER(9,2),
  PFADV_ARREAR_DEDUC   NUMBER(9,2),
  TEL_EXCESS_BILL      NUMBER(9,2),
  GEN_INSURENCE        NUMBER(9,2),
  SP_DEDUC             NUMBER(9,2),
  SP_DESCRIPTION       VARCHAR2(45),
  TREMARKS             VARCHAR2(35),
  DEARNESS_ALLOWANCE   NUMBER(9,2),
  ARREAR               NUMBER(9,2),
  OTHER_DEDUC          NUMBER(9,2),
  HBADV_DEDUC_PERCENT  NUMBER(5,2),
  TOT_SAL_ALLOWANCE    NUMBER(9,2),
  INCREMENT_DATE       DATE,
  ARREAR_BASIC         NUMBER(9,2),
  INSTL_AMT_TLO        NUMBER(9,2),
  INSTL_AMT_TLR        NUMBER(9,2),
  INSTL_AMT_INS        NUMBER(9,2),
  INSTL_AMT_INC        NUMBER(9,2),
  OFFICE_CODE          NUMBER(4),
  COMP_DEDUC           NUMBER(9,2),
  GENERATED_BY         VARCHAR2(15),
  GENERATED_ON         DATE
);

-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE PRMS_TRANSACTION
  ADD PRIMARY KEY (ENTITY_NUMBER, BRANCH_CODE, EMP_ID, SAL_YEAR, MONTH_CODE);
 
         
ALTER TABLE PRMS_TRANSACTION       
ADD   (INCOME_TAX     NUMBER(7,2),
       INCOME_TAX_ARR NUMBER(7,2));
ALTER TABLE PRMS_TRANSACTION ADD HILL_ALLWNC NUMBER(7,2);	   
	   
ALTER TABLE PRMS_TRANSACTION ADD ACTUAL_BASIC NUMBER(9,2);	   
	   
