-- CREATE TABLE
CREATE TABLE PRMS_EMP_SAL_HIST
(
  EMP_ID               VARCHAR2(20) NOT NULL,
  EFFECTIVE_DATE       DATE NOT NULL,
  EFT_SERIAL           NUMBER(3) NOT NULL,
  EMP_BRN_CODE         VARCHAR2(5),
  DESIG_CODE           NUMBER(2),
  DESIG                VARCHAR2(30),
  DESIG_SENIORITY_CODE NUMBER(3),
  INCREMENT_DATE       DATE,
  PAYSCALE_CODE        NUMBER(2),
  STATUS_CODE          VARCHAR2(3),
  TIME_SCALE           VARCHAR2(1),
  PF_TYPE              VARCHAR2(1),
  PF_DEDUCTION_PCT     NUMBER(5,2),
  HOUSE_RENT_PCT       NUMBER(5,2),
  BANK_CODE            NUMBER(2),
  MEDICAL_ALLOWANCE    NUMBER(7,2),
  SQ_RESIDENCE         VARCHAR2(1),
  PF_LIEN              VARCHAR2(1),
  SP_INSURANCE         NUMBER(7,2),
  PAYMENT_BANK         VARCHAR2(1),
  ACC_NO_ACTIVE        VARCHAR2(1),
  BASIC_APY            NUMBER(9,2),
  EMP_CATEGORY         NUMBER(1),
  BANK_ACC             VARCHAR2(25),
  DEARNESS_PCT         NUMBER(5,2),
  PEN_PCT              NUMBER(5,2),
  ARREAR_BASIC         NUMBER(9,2),
  NEW_BASIC            NUMBER(9,2),
  BONUS_YN             VARCHAR2(1),
  HBFC_OWN             VARCHAR2(1),
  LPR_LAST_DATE        DATE,
  ENTD_BY              VARCHAR2(15),
  ENTD_ON              DATE,
  MOD_BY               VARCHAR2(15),
  MOD_ON               DATE,
  TRANSFER_DATE        DATE,
  EMP_DEPT_CODE        NUMBER(3)
);
-- CREATE/RECREATE PRIMARY, UNIQUE AND FOREIGN KEY CONSTRAINTS 
ALTER TABLE PRMS_EMP_SAL_HIST
  ADD PRIMARY KEY (EMP_ID, EFFECTIVE_DATE, EFT_SERIAL);